### PR TITLE
React capstone project - Finland Cities

### PR DESCRIPTION
**Pull request by billymohajeri**
In this project,

✅ I Chose an API to base the development of the web app. The API allows me to get numeric values based on a parameter.
✅ I followed this [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)).
✅ I implemented the Home page: When the page loads, it shows a list of cities that could be filtered out by city name.
✅ On the details page, the web app retrieves data from the API to show detailed data about each city.
✅ When the user clicks on the "Back" button (<), the user navigates to the home page.
✅ I created unit tests for pure functions in your Redux code.
✅ I created integration tests for your application using the React Testing Library.
✅ The project is a single-page application (SPA) built with React and Redux.
✅ Every page (the main page and the pages for each item) have a unique route within the SPA.
✅ The project has been deployed and is accessible online.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @billymohajeri,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linters passed ✔️ 
- 3 tests passed ✔️ 
- Styling ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ]  I would recommend you add a piece of code that you have written that interests you in this project you have done to the video you made as it is a requirement of this project. You will need to record another video.
- [ ] I would advise you to give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by billymohajeri** [comment]
Hi @Olamarx,
First of all, thank you for the review 👍 

About the giving appropriate credit, I gave credit 2 times. One time in the project description and another time in the acknowledgments.
 
Screenshot 2023-02-09 105310

and 

Screenshot 2023-02-09 105341

Do you think I should change it?

Thanks 😎

**Comment by Olamarx** [comment]
Oh, my bad! I doubt if I saw it. Kindly go on with the second one. I am sorry for that.

**Comment by billymohajeri** [comment]
No it's totally fine, thanks again 👍

**Review by rotimiazeez — APPROVED** [review]
Hi @billymohajeri 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good video presentation 📹
- Descriptive README 📖
- No linter error ✅️
- Good UI design 🖼️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
